---
server:
  port: 1008
  context-path: /
spring:
  redis:
    database: 0
    host: 192.168.197.135
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 100
        max-idle: 3
        max-wait: -1
        min-idle: 0
    timeout: 1000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scp2p?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: microservice-member
  profiles: provider-hystrix-1008

eureka:
  instance:
    hostname: localhost
    appname: microservice-member
    instance-id: microservice-member:1008
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka2001.gg.com:2001/eureka/,http://eureka2002.gg.com:2002/eureka/

info:
  groupId: com.gg.p2pproject
  artifactId: microservice-member-provider-hystrix-1008
  version: 1.0-SNAPSHOT
  userName: http://gg.com
  phone: 123456

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1500
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  type-aliases-package: com.gg.microservicecommon.member.entity

---
server:
  port: 1009
  context-path: /
spring:
  redis:
    database: 0
    host: 192.168.239.131
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 100
        max-idle: 3
        max-wait: -1
        min-idle: 0
    timeout: 1000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scp2p?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: microservice-member
  profiles: provider-hystrix-1009

eureka:
  instance:
    hostname: localhost
    appname: microservice-member
    instance-id: microservice-member:1009
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka2001.gg.com:2001/eureka/,http://eureka2002.gg.com:2002/eureka/

info:
  groupId: com.gg.p2pproject
  artifactId: microservice-member-provider-hystrix-1009
  version: 1.0-SNAPSHOT
  userName: http://gg.com
  phone: 123456

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1500

mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  type-aliases-package: com.gg.microservicecommon.member.entity